### ISSUE TITLE
Add general_simplicial_set_intersection to the uwot API

### ISSUE THREAD

**Issue by jlmelville** [jlmelville/uwot#101]
From lmcinnes/umap#58:

> I am doing the following analysis in python and want to do the same in R
> 
> ```python
> import umap
> 
> X_reduced= PCA(n_components = 20).fit_transform(X)
> Y_reduced = PCA(n_components = 10).fit_transform(Y)
> 
> fit1 = umap.UMAP(n_components = 2, min_dist = 1, n_neighbors = 93, n_epochs = 1000, 
>                  init = X_reduced[:, 0:2], 
>                  verbose = 2).fit(X_reduced)
> fit2 = umap.UMAP(n_components = 2, min_dist = 0.8, n_neighbors = 93, n_epochs = 1000, 
>                  init = Y_reduced[:, 0:2], 
>                  verbose = 2).fit(Y_reduced)
> intersection = umap.umap_. general_simplicial_set_intersection(fit1.graph_, 
>                                                                fit2.graph_, 
>                                                                weight = 0.45)
> intersection = umap.umap_.reset_local_connectivity(intersection)
> embedding = umap.umap_.simplicial_set_embedding(fit1._raw_data, intersection, 
>                                                 fit1.n_components, 
>                                                 fit1.learning_rate, 
>                                                 fit1._a, fit1._b, 
>                                                 fit1.repulsion_strength, 
>                                                 fit1.negative_sample_rate, 
>                                                 1000, 'random', np.random, 
>                                                 fit1.metric, 
>                                                 fit1._metric_kwds, False)
> ```
> I wish to replicate the following operation in R. Is there a way?

It is not possible to do this at the moment, because although a suitable (internal) function to the set intersection exists, there isn't a convenient function do the optimization of the low dimensional coordinates (see #98).

**Comment by jlmelville** [comment]
@ratheraarif a few months ago at https://github.com/lmcinnes/umap/issues/58#issuecomment-1253795090 you asked for the ability to combine the fuzzy simplicial sets/graphs in R. The development version of uwot now has `simplicial_set_intersect` and `simplicial_set_union` to combine UMAP graphs, and follows the `__mul__` and `__add__` operators (but without doing any optimization of low dimensional coordinates).

It will appear in the next CRAN version if you don't want to install from github. Roughly, the R equivalent of the Python code you gave would be:

```R
graph1 <- similarity_graph(X_reduced, n_neighbors = 93)
graph2 <- similarity_graph(Y_reduced, n_neighbors = 93)
intersection <- simplicial_set_intersect(graph1, graph2, weight = 0.45)

embedding <- optimize_graph_layout(intersection , X = X_reduced, min_dist = 1, init = "random", n_epochs = 1000)
```

You don't need to call `reset_local_connectivity` because the intersection/union operations do that for you. Note also that most of the initialization and optimization options that you provided in the `UMAP` constructor example have no effect on the result because the low dimensional output isn't used in the intersection.

**Comment by ratheraarif** [comment]
😊

**Comment by jlmelville** [comment]
This got added so I am going to close this
