### ISSUE TITLE
devtools can no longer build uwot on Windows

### ISSUE THREAD

**Issue by jlmelville** [jlmelville/uwot#108]
Running `devtools::load_all(".")` now results in messages like:

```
as: r_uwot.o: too many sections (35834)
Assembler messages:
Fatal error: can't write 26 bytes to section .text of r_uwot.o: 'file too big'
```

indicate my template-hungry coding style in uwot has finally come back to haunt me (possibly in combination with recent dependency version changes?). According to <https://digitalkarabela.com/mingw-w64-how-to-fix-file-too-big-too-many-sections/>, the solution is to add a linker directive `-mbig-obj` e.g. something like:

```Make
PKG_CXXFLAGS += -Wa,-mbig-obj
```

to `Makevars.win`. It now takes a noticeably longer time to build, predictably in the linking part. Worse, `devtools::check()` reports:

```
N  checking compilation flags used
   Compilation used the following non-portable flag(s):
     '-Wa,-mbig-obj'
```

Uh-oh. While only a `NOTE`, I don't relish explaining that one to the CRAN maintainers. Well, we had a good run. I'll just have to re-write uwot to use pointers. See you in 2045.

**Comment by LTLA** [comment]
I don't recall seeing that many templates in your C++ code. Certainly it's not as bad as anything using Eigen or any of those header-only libraries floating around on CRAN. Surely they would be hit harder by template-related limitations.

**Comment by jlmelville** [comment]
It's a mingw problem it seems. Running `devtools::load_all` under Linux doesn't give a problem.

Good point about Eigen. Maybe it's because `src/r_uwot.cpp` basically generates all combinations of the templated classes: `r_uwot.o` and `uwot.dll` end up at > 32MB in size.

**Comment by LTLA** [comment]
If major surgery on **uwot**'s C++ code is required... maybe you might consider whether **umappp** might be a good place to put that effort? It might be possible to achieve the dream of consolidating all the C++ code floating around into a central library that can be re-used elsewhere (e.g., LTLA/umappp#5).

Happy to give you maintainer access, I pretty much copied **uwot**'s code anyway, though I did strip out TBB in favor of `std::thread` and/or OpenMP. I don't think I used much templating either.

Anyway, just a thought, no pressure.

**Comment by jlmelville** [comment]
Moving over to umappp is a good idea (I also moved to only using `std::thread` a while ago). But I probably can't make the change for uwot without breaking backwards compatibility or adding a lot of stuff that no-one would want in umappp. So I will have to work out how to split that up.

In the current code base there are some templated things that only get called once an epoch and which can be made pointer-based, which might buy me some time.

**Comment by jlmelville** [comment]
Ok I bought myself some time by removing a gradient instantiation
