### ISSUE TITLE
List of metrics not allowed if X is a matrix.

### ISSUE THREAD

**Issue by OuNao** [jlmelville/uwot#20]
List of metrics not allowed if X is a matrix.

I tried the option metric=list("cosine"=1:27, "categorical"=28) on my data (matrix with dimnames) and got this error:

Error in match.arg(metric, c("euclidean", "cosine", "manhattan", "hamming", : 'arg' should be one of “euclidean”, “cosine”, “manhattan”, “hamming”, “precomputed”

If I set X=as.data.frame(mydata) the error is gone.

Thanks.

**Comment by OuNao** [comment]
Maybe this line:
https://github.com/jlmelville/uwot/blob/master/R/uwot.R#L1089
Could be:
if (methods::is(X, "data.frame") || methods::is(X, "matrix")) {

**Comment by jlmelville** [comment]
Thanks for the report. I have added the fix to master.

To be on the safe side, I would always recommend converting `X` to a data frame and explicitly converting any column you want to be treated as categorical to a factor.

**Comment by jlmelville** [comment]
Pretty sure this is fixed. Please re-open if not.
