### ISSUE TITLE
Error installing uwot under Microsoft R

### ISSUE THREAD

**Issue by fabix71** [jlmelville/uwot#21]
Hello,

  i'm trying to install in this environment 
  CentOS 7.6.1810 - gcc 4.8.5
  Microsoft R 3.5.1
  but I receive this error
  
  > devtools::install_github("jlmelville/uwot")
Downloading GitHub repo jlmelville/uwot@master
from URL https://api.github.com/repos/jlmelville/uwot/zipball/master
Installing uwot
'/opt/microsoft/ropen/3.5.1/lib64/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpWTJkQy/devtools1bf444ad5fb01/jlmelville-uwot-05e3d4e'  \
  --library='/opt/microsoft/ropen/3.5.1/lib64/R/library' --install-tests

* installing *source* package ‘uwot’ ...
** libs
g++ -std=gnu++11 -I/opt/microsoft/ropen/3.5.1/lib64/R/include -DNDEBUG  -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/Rcpp/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppProgress/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppAnnoy/include" -DU_STATIC_IMPLEMENTATION  -DRCPP_PARALLEL_USE_TBB=1 -DSTRICT_R_HEADERS -fpic  -DU_STATIC_IMPLEMENTATION -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I/opt/microsoft/ropen/3.5.1/lib64/R/include -DNDEBUG  -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/Rcpp/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppProgress/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppAnnoy/include" -DU_STATIC_IMPLEMENTATION  -DRCPP_PARALLEL_USE_TBB=1 -DSTRICT_R_HEADERS -fpic  -DU_STATIC_IMPLEMENTATION -g -O2 -c connected_components.cpp -o connected_components.o
g++ -std=gnu++11 -I/opt/microsoft/ropen/3.5.1/lib64/R/include -DNDEBUG  -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/Rcpp/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppProgress/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppAnnoy/include" -DU_STATIC_IMPLEMENTATION  -DRCPP_PARALLEL_USE_TBB=1 -DSTRICT_R_HEADERS -fpic  -DU_STATIC_IMPLEMENTATION -g -O2 -c gradient.cpp -o gradient.o
g++ -std=gnu++11 -I/opt/microsoft/ropen/3.5.1/lib64/R/include -DNDEBUG  -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/Rcpp/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppProgress/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppAnnoy/include" -DU_STATIC_IMPLEMENTATION  -DRCPP_PARALLEL_USE_TBB=1 -DSTRICT_R_HEADERS -fpic  -DU_STATIC_IMPLEMENTATION -g -O2 -c nn_descent.cpp -o nn_descent.o
g++ -std=gnu++11 -I/opt/microsoft/ropen/3.5.1/lib64/R/include -DNDEBUG  -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/Rcpp/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppProgress/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include" -I"/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppAnnoy/include" -DU_STATIC_IMPLEMENTATION  -DRCPP_PARALLEL_USE_TBB=1 -DSTRICT_R_HEADERS -fpic  -DU_STATIC_IMPLEMENTATION -g -O2 -c nn_parallel.cpp -o nn_parallel.o
nn_parallel.cpp: In function ‘Rcpp::List annoy_hamming_nns(const string&, const NumericMatrix&, std::size_t, std::size_t, std::size_t, bool)’:
nn_parallel.cpp:129:31: error: ‘Hamming’ was not declared in this scope
   NNWorker<int32_t, uint64_t, Hamming, Kiss64Random>
                               ^
nn_parallel.cpp:129:52: error: template argument 3 is invalid
   NNWorker<int32_t, uint64_t, Hamming, Kiss64Random>
                                                    ^
nn_parallel.cpp:130:11: error: invalid type in declaration before ‘(’ token
     worker(index_name, mat, dist, idx, ncol, n, search_k);
           ^
nn_parallel.cpp:130:57: error: expression list treated as compound expression in initializer [-fpermissive]
     worker(index_name, mat, dist, idx, ncol, n, search_k);
                                                         ^
nn_parallel.cpp:132:56: error: invalid initialization of reference of type ‘RcppParallel::Worker&’ from expression of type ‘int’
   RcppParallel::parallelFor(0, nrow, worker, grain_size);
                                                        ^
In file included from nn_parallel.cpp:3:0:
/opt/microsoft/ropen/3.5.1/lib64/R/library/RcppParallel/include/RcppParallel.h:30:13: error: in passing argument 3 of ‘void RcppParallel::parallelFor(std::size_t, std::size_t, RcppParallel::Worker&, std::size_t)’
 inline void parallelFor(std::size_t begin, std::size_t end,
             ^
make: *** [nn_parallel.o] Error 1
ERROR: compilation failed for package ‘uwot’
* removing ‘/opt/microsoft/ropen/3.5.1/lib64/R/library/uwot’
Installation failed: Command failed (1)
>

i've googled but i couldn't find any solutions, i hope you may kindly help with my issue.
regards,
Fabio

**Comment by jlmelville** [comment]
Hello, thank you for the report. What version of [RcppAnnoy](https://cran.r-project.org/package=RcppAnnoy) is installed? Hamming support requires 0.0.11, which was only released at the end of November. I suspect that is the problem.

Short term, I am going to add a version dependency for now to hopefully make the error clearer, although that won't help with installing on Microsoft R. To solve the problem will require making Hamming support optional, which will take me a bit longer.

**Comment by fabix71** [comment]
Hi James,
  I really appreciate your support, in fact after issuing install.package("RcppAnnoy") from within MRO, the version installed is
> packageVersion("RcppAnnoy")
[1] ‘0.0.10’
I suppose I can't hope to make Microsoft R just installing the latest version.
The strange is that at https://mran.microsoft.com/package/RcppAnnoy the version available is 0.0.11!

regards,
Fabio

**Comment by fabix71** [comment]
Hi James,
  i believe this may be a workaround 
  issuing 
> >checkpoint("YYYY-MM-DD") 
  within MRO

**Comment by jlmelville** [comment]
I'm glad that you found a workaround and it's acceptable for you, although obviously one of the points of using MRO is to have a frozen set of packages that don't suddenly change out from under the user, so I should probably still look at what I can do to allow the Hamming support to be optional.

**Comment by csetraynor** [comment]
Download the latest version from source here https://cran.r-project.org/src/contrib/Archive/RcppAnnoy/ was the solution for me.

**Comment by jlmelville** [comment]
As of February 2020, the MRAN version of RcppAnnoy is up to 0.0.13 which does support Hamming distances (<https://mran.microsoft.com/package/RcppAnnoy>), so I am I going to close this.
