### ISSUE TITLE
nn_method = 'FNN' is incompatible with ret_model = TRUE

### ISSUE THREAD

**Issue by OuNao** [jlmelville/uwot#24]
Hi,

Maybe this is a "no issue".
I´m trying FNN as method for kNN search and need ret_model = TRUE to do metric learning, but I get a error:

Error in x2nn(X, n_neighbors, metric, nn_method, n_trees, search_k, n_refine_iters,  : 
  nn_method = 'FNN' is incompatible with ret_model = TRUE

Do you think there could be a workaround?

Thanks.

**Comment by jlmelville** [comment]
Unfortunately, FNN doesn't provide a data structure that can be used to query new data. For small datasets, you can force the use of Annoy with `nn_method = "annoy"`.

**Comment by OuNao** [comment]
Ok.
I will do this.

Another question: are there any option to pass do annoy to search for exact NN?

Thanks again.

**Comment by jlmelville** [comment]
No, your only option is to set `search_k` and `n_trees` to larger values.

There are some private functions in uwot, `uwot:::FNN_nn` (which uses FNN) and `uwot:::annoy_nn` (which uses Annoy), that you could use to benchmark the Annoy settings. They will return a list containing a matrix of neighbor indices and distances. The input to both these functions already needs to be a matrix, not a dataframe (another private function, `uwot:::x2m` can help with that if needed). 

```R
mat <- uwot:::x2m(df)
true_nn <- uwot:::FNN_nn(mat, k = 15)
approx_nn <- uwot:::annoy_nn(mat, k = 15, n_trees = 100)
# compare contents of approx_nn$idx with true_nn$idx
```

**Comment by OuNao** [comment]
I will try these to find the best values for my data.

Thank you.
