### ISSUE TITLE
umap_transform and tumap

### ISSUE THREAD

**Issue by jeky82** [jlmelville/uwot#30]
Hi,
If i run umap_trasform after tumap I get the following error

16:25:52 Writing NN index file to temp file /tmp/RtmpAAapHI/file3b610733a05

Error in .External(list(name = "CppMethod__invoke_void", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address 

while instead everything works if I use umap and then umap_trasform. Of course using the same data  for both methods.

**Comment by jlmelville** [comment]
I'm not able to reproduce this. Some questions:

* what version of `uwot` are you using? Installed from github or CRAN?
* what version of RcppAnnoy are you using?
* are you saving or loading or restarting the session between calling `umap`/`tumap` and `umap_transform`?
* if you evaluate the `nn_index` value of the returned model in both cases, what does it look like? For example:
```R
> model <- umap(....); model$nn_index
C++ object <0000026366d65520> of class 'AnnoyEuclidean' <0000026366b881c0>`
```

**Comment by dibbelab** [comment]
Sorry, was my mistake. The object was saved a reloaded in an other R session. Indeed If I rerun tumap on the data everything works fine. When I load the object that contain the umap model if I exec your test on nn_index this is what I get

```R
> data$uwot_model$nn_index
Error in sprintf("C++ object <%s> of class '%s' <%s>", externalptr_address(pointer),  : 
  external pointer is not valid
```

The object data is a list and contains original data and uwot model plus few other stuff. I saved it with saveRDS. Is not a issue, but just for curiosity is there a way to avoid this behaviour?

Anyway, really thank you for the help.

**Comment by jlmelville** [comment]
Unfortunately, the nearest neighbor index memory is owned by the C++ code and is opaque to R, so `saveRDS` and `loadRDS` don't work with `uwot` models.

To serialize/deserialize the models use the `save_uwot` and `load_uwot` functions.
