### ISSUE TITLE
uwot 0.1.4 is failing to compile on RStudio Server Pro (RHEL 7)

### ISSUE THREAD

**Issue by mjsteinbaugh** [jlmelville/uwot#32]
Hi @jlmelville, I'm hitting a compilation issue with uwot 0.1.4 on my RStudio Server Pro installation, running on Azure / RHEL 7.

Specifically with RStudio Server Pro, I'm seeing this failure:

```r
install.packages("uwot")
```

```
g++ -std=gnu++11 -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o uwot.so RcppExports.o connected_components.o gradient.o nn_parallel.o optimize.o perplexity.o sampler.o smooth_knn.o supervised.o transform.o WARNING: ignoring environment value of R_HOME -L/usr/local/lib64/R/lib -lR
g++: error: WARNING:: No such file or directory
g++: error: ignoring: No such file or directory
g++: error: environment: No such file or directory
g++: error: value: No such file or directory
g++: error: of: No such file or directory
g++: error: R_HOME: No such file or directory
make: *** [uwot.so] Error 1
ERROR: compilation failed for package ‘uwot’
* removing ‘/data00/R/site-library/3.6/uwot’
* restoring previous ‘/data00/R/site-library/3.6/uwot’
Warning in install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘uwot’ had non-zero exit status
Calls: install ... <Anonymous> -> .install -> .install_repos -> install.packages
```

However, on another virtual machine running regular RStudio Server (RHEL 7), the package installs fine. The failure is due to the `R_HOME` variable not being detected as expected. Any tips on how to fix this?

**Comment by mjsteinbaugh** [comment]
Forcing `R_HOME` (which is normally unset in my shell) does no good:

```sh
wget https://cran.r-project.org/src/contrib/uwot_0.1.4.tar.gz
export R_HOME="/usr/local/lib64/R"
R CMD INSTALL uwot_0.1.4.tar.gz
```

```
WARNING: ignoring environment value of R_HOME
```

**Comment by mjsteinbaugh** [comment]
Yeah I see @LTLA's comment in #29 and that's definitely the issue I'm seeing on my end. Just wanted to give you a heads up. Thanks!

**Comment by jlmelville** [comment]
Thanks for the detective work, @mjsteinbaugh. I know nothing of RStudio Server Pro. Were you involved with its installation on that machine, so is there any indication that R on that machine was built from source in the way described in the post you found that would cause issues with `Rscript` or do you think this is a separate issue that might cause people to see this message?

**Comment by mjsteinbaugh** [comment]
In case anybody else comes across this issue, RStudio install was from RPM image here:
https://www.rstudio.com/products/rstudio/download-commercial/

**Comment by mjsteinbaugh** [comment]
RStudio Server Pro does some weird non-standard things to handle multiple R versions, and I think that may be the root of the problem here. I have no trouble with uwot on any of my other machines.
