### ISSUE TITLE
Add github contributors to DESCRIPTION

### ISSUE THREAD

**Issue by jlmelville** [jlmelville/uwot#36]
@sirusb, @ttriche: as contributors of PRs to this package, would you like to be acknowledged as such in the `Authors@R` field of the `DESCRIPTION`? You don't need to provide an email address, just a suitable identifier, e.g. first name and last name. For reference, the field currently looks like:

```R
    c(person("James", "Melville", email = "jlmelville@gmail.com", role = c("aut", "cre")),
    person("Aaron", "Lun", role="ctb"))
```

**Comment by sirusb** [comment]
Hi @jlmelville  Thank you very much for the generous offer, however, I don't think that my two lines edits qualify me to be listed as a  contributor in the package development :).

**Comment by LTLA** [comment]
Aw gee @sirusb, your principles are making me look bad :)

**Comment by sirusb** [comment]
Hi Aaron (@LTLA), no, no, you definitely deserve it :). I added myself :)

**Comment by jlmelville** [comment]
Thanks @sirusb :)
