### ISSUE TITLE
 Incorrect number of arguments for '_uwot_smooth_knn_distances_parallel'

### ISSUE THREAD

**Issue by markgrujic** [jlmelville/uwot#4]
Hi James,

Great package, appreciate the efforts! It looks like the latest version is broken though?

`umap(iris[,1:4])`

results in the error:
`Error in .Call(`_uwot_smooth_knn_distances_parallel`, nn_dist, nn_idx,  : 
  Incorrect number of arguments (10), expecting 9 for '_uwot_smooth_knn_distances_parallel'`

I didn't have issues until today. Any idea about what might be causing this?

Cheers

**Comment by jlmelville** [comment]
Hello, sorry to hear you are having trouble. I'm not able to re-produce this, and the tests being run on the CIs *should* cover this code path.

A couple of days ago, I did a big refactoring to remove duplicated C++ code, which resulted in adding a new argument to `smooth_knn_distances_parallel` (and similar functions). I've noticed with some packages that I update with `devtools::install_github`, that I sometimes see stale versions of functions unless I completely uninstall the package, restart my session and reinstall. Maybe this is happening here?

If you are using the package via devtools, could you try completely removing the package via:
```R
remove.packages("uwot")
```
then restart your session (in RStudio at least I have to quit and restart to see the changes), and reinstall:
```R
devtools::install_github("jlmelville/uwot")
```
If you are working with the project directly e.g. via RStudio, then try deleting `src/RcppExports.cpp` and then rebuild via `devtools::load_all(".")`. If you are still having problems, it might be useful to see the output of: 
```R
uwot:::smooth_knn_distances_parallel
```

**Comment by markgrujic** [comment]
Thanks, removing and reinstalling works as expected. In hindsight, should've gone straight to that!
Cheers
