### ISSUE TITLE
uwot::umap_transform not producing same results as those in python implementation

### ISSUE THREAD

**Issue by moldach** [jlmelville/uwot#41]
I've noticed that I'm not getting similar results from the `uwot` as the [python implementation](https://github.com/lmcinnes/umap).

**Goal**: Translate a pipeline from Python to R.
**Problem**: `uwot` behaves different than `umap` (python)

For reproducibility, I'm following [this workflow in python](https://gdmarmerola.github.io/umap-supervised-embeddings/?lipi=urn%3Ali%3Apage%3Ad_flagship3_detail_base%3BaSleEZS7CB%2FEslVrVGc4FA%3D%3D). 

Prior to the supervised clustering with `umap` there are two steps 1) simulating data with `sklearn.datasets.make_classification()` and 2) scaling with `StandardScaler.fit_transform()`. 

Rather than simulating data and scaling with `R` functions lets use python so the input to `uwot` and Python's `umap` are identical.

First we simulate the data and scale it with Python. Let's enter the python interpreter with `repl_python() then enter the following:

```
 # importing relevant libraries
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier 
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import cross_val_predict, StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.datasets import make_classification
from tqdm import tqdm
from umap import UMAP
from pynndescent import NNDescent
from fastcluster import single
from scipy.cluster.hierarchy import cut_tree, fcluster, dendrogram
from scipy.spatial.distance import squareform
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier

# let us generate some data with 10 clusters per class
X, y = make_classification(n_samples=500000, n_features=200, n_informative=5, 
                           n_redundant=0, n_clusters_per_class=10, weights=[0.80],
                           flip_y=0.05, class_sep=3.5, random_state=42)

# normalizing to eliminate scaling differences
X = pd.DataFrame(StandardScaler().fit_transform(X))
```

Were going to want to do Python's `umap` first but we will do the plotting in `ggplot2` just to show that it's not an issue with visualization.

```
# building supervised embedding with UMAP
sup_embed_umap = UMAP().fit_transform(X, y=y)

exit # exit the python interpreter
```

Now let's plot this in R:

```
library(ggplot2)

unsup_embed_python <- py$unsup_embed
unsup_embed_python <- as.data.frame(unsup_embed_python)
unsup_embed_python$labels <- py$y

ggplot(sup_embed_python, aes(V1, V2, color = labels)) + geom_point() + scale_color_manual(values = c("#0000FF", "#ff0000"))
```

Here's what it looks like:
![python-result](https://user-images.githubusercontent.com/5749465/70544245-c3c86f00-1b39-11ea-9ebc-422e524111ef.png)

Now let's do the same thing using the default for supervised dimension reduction with `uwot`:

```
sup_embed_R <- umap(py$X, y = py$y)
sup_embed_R <- as.data.frame(sup_embed_R)
sup_embed_R$labels <- py$y
ggplot(sup_embed_R, aes(V1, V2, color = as.character(labels))) + geom_point() + scale_color_manual(values = c("#0000FF", "#ff0000"))
```

The resulting image looks identical to calling `uwot` **without** supervision (`y = py$y`)?

![crappo](https://user-images.githubusercontent.com/5749465/70544331-e0fd3d80-1b39-11ea-88bb-a68854f16c9e.png)

I [read the "**Python Comparison**" document](https://jlmelville.github.io/uwot/pycompare) which suggests using `pca = 100` and `min_dist = 0.1` within `umap()`. So I also tried this but don't see a similar result.

```
sup_embed_R <- umap(py$X, y = py$y, pca = 100, min_dist = 0.1)
sup_embed_R <- as.data.frame(sup_embed_R)
sup_embed_R$labels <- py$y
ggplot(sup_embed_R, aes(V1, V2, color = as.character(labels))) + geom_point() + scale_color_manual(values = c("#0000FF", "#ff0000"))
```

![crap2](https://user-images.githubusercontent.com/5749465/70550933-8ddcb800-1b44-11ea-8ad0-9b2b582e0d2e.png)

Maybe the issue is that Python is calling the `fit_transform()` function from `umap`. Therefore, I tried using the `ret_model = TRUE` with `uwot::umap_transform()` but I don't get the same result as python either. 

```
sup_embed_model <- uwot::umap(py$X, y = py$y, ret_model = TRUE)
sup_embed_R <- uwot::umap_transform(py$X, sup_embed_model, verbose = TRUE)
sup_embed_R <- as.data.frame(sup_embed_R)
sup_embed_R$labels <- py$y

ggplot(sup_embed_R, aes(V1, V2, color = as.character(labels))) + geom_point() + scale_color_manual(values = c("#0000FF", "#ff0000"))
```
This [looks more like a *donut* than two separate cluster](https://i.ibb.co/GJc2bWC/weird-transform.png)

![weird_transform](https://user-images.githubusercontent.com/5749465/70544207-b3b08f80-1b39-11ea-9984-37b07f5b4d83.png)

Is there something I'm doing wrong?

**Comment by jlmelville** [comment]
I'd say that the `py$y` array, because it contains numeric 1s and 0s, is being interpreted as containing numeric values, not categorical values. Convert them to a factor and you should see the results you are expecting:

```R
sup_embed_R <- umap(py$X, y = factor(py$y))
```

**Comment by moldach** [comment]
Wow that was a quick and very accurate response. Converting to a factor solved the issue - thanks!
