### ISSUE TITLE
To run umap using external pca components

### ISSUE THREAD

**Issue by Harini-107** [jlmelville/uwot#42]
I tried to run umap with init parameter as a matrix that had pca components generated from another software.But the initialisation failed and ran with random instead.

**Comment by SamGG** [comment]
Hi,
It's always better to provide a code to understand the question.
I think you will find an answer below or it will help you specifying precisely your question.
Best.
```
library(uwot)
plot(umap(iris[,-5]), col = iris[,5], asp = 1)
# in-house pca
plot(umap(iris[,-5], init = "pca"), col = iris[,5], asp = 1)
# external PCA
init = prcomp(iris[,-5])
plot(init$x)
# specify the exact components
plot(umap(iris[,-5], init = init$x[,1:2]), col = iris[,5], asp = 1)
```

**Comment by SamGG** [comment]
@jlmelville Maybe it would be interesting to report about the dimension of the init matrix.

**Comment by jlmelville** [comment]
@SamGG, if the dimensions of `init` aren’t `nrows x n_components` an error will be thrown so that shouldn’t be the problem in this case. @Harini-107, can you provide the command you ran.

**Comment by Harini-107** [comment]
Hi all,
This is my PC and data file
![pcfile](https://user-images.githubusercontent.com/58587394/70772607-0f2d8800-1d9b-11ea-975e-ae3424f52555.png)
![datafile](https://user-images.githubusercontent.com/58587394/70772608-0f2d8800-1d9b-11ea-88b9-ecee3b8651d5.png)

This is the code snippet:
library(uwot)
#Reading in pca file and transposed it
p=read.table(file="pca.tsv",header=T,row.names=1)
p1=as.data.frame(t(p))
#Reading in data file and transposed it
d=read.table(file="917cells.txt",header=T,row.names=1)
d1=as.data.frame(t(d))
#running umap with p1
u=umap(d1,init=p1)
#Throws error message
**Error in match.arg(tolower(init), c("spectral", "random", "lvrandom",  : 
  'arg' must be of length 1**
But when I tried this with iris data it works fine.Can someone explain this

**Comment by jlmelville** [comment]
@Harini-107, the `init` argument must be a `matrix`, not a `data.frame`. Try doing:

```R
p1 <- as.matrix(t(p))
```

You should also only use as many columns as you have specified `n_components`, which is the dimensionality of the output (nothing to do with principal components). If you are reducing the number of dimensions down to 2, then you should only keep the first two PCs:

```R
p1 <- as.matrix(t(p))[, 1:2]
```

It's not a very helpful error message in this case. I will fix this. Thank you for reporting this.

**Comment by Harini-107** [comment]
Thank You I am able to run umap for the samples now

**Comment by SamGG** [comment]
As a reminder, here are the error codes.
```
> plot(umap(iris[,-5], init = init$x), col = iris[,5], asp = 1)
Error in uwot(X = X, n_neighbors = n_neighbors, n_components = n_components,  : 
  init matrix does not match necessary configuration for X
> plot(umap(iris[,-5], init = as.data.frame(init$x[,1:2])), col = iris[,5], asp = 1)
Error in match.arg(tolower(init), c("spectral", "random", "lvrandom",  : 
  'arg' must be of length 1
```
@jlmelville IMHO the 1st one does not clearly indicate the matrix size.
@Harini-107 IMHO the error code does not lead to a successful run with a random seed.

**Comment by jlmelville** [comment]
@SamGG, those errors have been improved a bit on master. I would welcome any feedback.

**Comment by SamGG** [comment]
@jlmelville Nice improvement. Thanks.
