### ISSUE TITLE
possible to use multiple y variables ? 

### ISSUE THREAD

**Issue by akhst7** [jlmelville/uwot#43]
HI, 

For supervised dimension reduction,    are multiple y variables  allowed ?  I did `y=c(y1, y2)` and got an error.  

Thanks.

**Comment by jlmelville** [comment]
Hello, yes that should be supported. Try making a dataframe from `y1` and `y2`, e.g. (`y=data.frame(y1=y1, y2=y2)`). Does that work?

**Comment by akhst7** [comment]
@jlmelville ,  it worked beautifully 

Thanks.
