### ISSUE TITLE
Error when input data is not of a right-numbered column?

### ISSUE THREAD

**Issue by heelarryous** [jlmelville/uwot#51]
Hi there,
I'm getting a weird error when I try to run umap() with my data:
`Error: index size 79464 is not a multiple of vector size 16`
After playing around trying to figure out why (iris data was working), I discovered that it has something to do with the number of columns that your input data for umap() is.

As an example, when you eliminate one of the numeric columns of the iris dataset (from 4 to 3), I also get a similar error.

```
iris_train <- data.table(iris[1:100, 1:3])
iris_test <- data.table(iris[101:150, 1:3])

iris_train_umap <- umap(iris_train, n_components = 3, ret_model = T)
save_uwot(iris_train_umap, "~/iris.uwot")
Warning messages:
1: invalid uid value replaced by that for user 'nobody' 
2: invalid gid value replaced by that for user 'nobody' 
iris_umap = load_uwot("~/iris.uwot")
Error: index size 77420 is not a multiple of vector size 16

iris_test_umap <- umap_transform(iris_test, iris_umap)
```
Rstudio crashes.

Any help would be appreciated!

**Comment by heelarryous** [comment]
Sorry, just to add on to this, if I don't need to save the uwot object, umap_transform() doesn't give error. So there's something about saving the object and trying to re-load it that messes this up.

**Comment by jlmelville** [comment]
This is the same problem as #31.

The current GitHub master should have a fix. It will be in the next version on CRAN (although that is blocked by #50).

There is a potential workaround described in #31, but it is rather fiddly I’m afraid.

**Comment by heelarryous** [comment]
oh I'm sorry I must have missed that. Thanks so much, the master repo worked!
