### ISSUE TITLE
Error in FNN::get.knn(X, k) : Data include NAs

### ISSUE THREAD

**Issue by akhst7** [jlmelville/uwot#56]
Hi, 

I have a matrix with a size of 174, 76 and the last column contains 4 NAs.  I though uwot have tolerance for NAs in x but I get this error message, "FNN::get.knn(X, k) : Data include NAs".  I am using the following command;
`umap1<-umap(DT[,28:102], n_neighbors = 10, learning_rate = 0.5, init = "lvrandom", scale = "Z", a=1, b=0.5, min_dist = 1, spread = 4) %>% as.data.table()`

Is there any way to get around this NA issue ? 

Thanks.

**Comment by jlmelville** [comment]
I don't think there is a way around this except to filter out columns with NA in or do something domain-specific, e.g. replace the missing values with the means of the non-missing data and so on.

**Comment by akhst7** [comment]
So there is no way to implement `na.rm=T`, in the code and missing values must be imputed.    I am new to the UMAP algorithm but how does one single NA amongst hundreds and thousands of data points  suppress construction UMAP ?

**Comment by SamGG** [comment]
jlmelville answer is definitively the right one. You (or your expert) know exactly the best way to replace those missing values, better than any algorithm.
If you want an automatic imputation, there are many, starting by approaches based on knn.
If you believe that using PCA before UMAP is permitted, you could try NIPALS algorithm that is tolerant to missing values. I never used it but there is a R package https://cran.r-project.org/web/packages/nipals/nipals.pdf

**Comment by akhst7** [comment]
@SamGG,  thanks for your input.  I use Hmisc, misForest, and Ann to do imputation.  They all have pros and cons, and I have to play with imputed data.  Also, I will try NIPALS and put PCA results on UMAP and see.  Thanks.

**Comment by ivokwee** [comment]
One way would be to build a correlation matrix that allow missing values like in R  `cor(X, use='pairwise.complete')` then passing this to UMAP. Some remaining NA can exists and can be set to zero. Disadvantage is that for a million points you would need to create 1e6x1e6 distance matrix. It would be nice if UWOT implements the correlation with pairwise.complete as in R. Would this be possible?

**Comment by jlmelville** [comment]
> It would be nice if UWOT implements the correlation with pairwise.complete as in R. Would this be possible?

It's not something I foresee adding to uwot. Perhaps there is something I am missing, but the way I see it is:

First, a correlation matrix is a measure of similarity, and UMAP uses distance, although that's easy enough to deal with by defining the distance as 1 - correlation.

Second, a correlation distance is a very specific distance that wouldn't be applicable in cases when people want e.g. Euclidean or cosine distance, which is most of the time.

Third, both theoretically and practically UMAP does not calculate all possible pairs of distances (e.g. see Definition 9 in the paper), hence the `n_neighbors` parameter, so it's a lot of extra computation to do especially as you must then do extra work to find the k-nearest neighbors, which I have not implemented efficiently in the case of a distance matrix.

Fourth, as you mention, this approach doesn't scale very well.

As noted by Leland McInnes in https://github.com/lmcinnes/umap/issues/115, there are lots of causes of why data is missing and there is no one perfect way to handle it. I remain skeptical that uwot should be in the business of making these decisions for the user.

If the correlation matrix approach works for your (presumably quite small) data, then the following doesn't seem *that* onerous a pre-processing task (using `iris` as the example):

```R
iris_corm <- cor(t(iris[, -5]), use='pairwise.complete')
iris_corm[is.na(iris_corm)] <- 0
iris_corm <- as.dist(1.0 - iris_corm)

result <- umap(iris_corm)
```

Worth noting that if `X` is the data matrix with observations in rows, you *don't* want to pass it directly to `cor` as you will get the D * D matrix of correlations of the columns/features *not* the N * N matrix of correlations between the observations, you will need to transpose it first. As I say, maybe I am missing something.
