### ISSUE TITLE
umap_transform function

### ISSUE THREAD

**Issue by DanSchnell** [jlmelville/uwot#57]
Could you point me to something that generally explains how the umap_transform does the embedding of the new data, e.g. what information from the embedding of the initial set is used, what is the nature of the objective function that is being minimized?  I have gone thru the R code for the function but not getting it.

I have read (and generally understand) the "How UMAP works" description at https://umap-learn.readthedocs.io/en/latest/how_umap_works.html, so I have the basic idea of how the embedding of the initial set of data is done.

Any help would be appreciated!

**Comment by jlmelville** [comment]
Hi @DanSchnell, I replied in https://github.com/lmcinnes/umap/issues/384.

**Comment by DanSchnell** [comment]
Thanks very much James!!
