### ISSUE TITLE
uwot fails with a 5Mx27 matrix

### ISSUE THREAD

**Issue by qihaocytobank** [jlmelville/uwot#61]
I wonder what is the largest data matrix can the current implementation of uwot can handle? We tried uwot with a matrix that has 5M rows and 27 columns on an AWS VM machine. The VM has 64GB RAM and 16 CPU threads. The analysis can't be completed and stops during optimization. 

Here are some log messages.

15:54:30 Building Annoy index with metric = euclidean, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
16:11:04 Writing NN index file to temp file XXXXX
16:11:06 Searching Annoy index using 15 threads, search_k = 5000
16:20:25 Annoy recall = 100%
16:20:27 Commencing smooth kNN distance calibration using 15 threads
16:33:41 Initializing from uniform random
16:34:24 Commencing optimization for 200 epochs, with 384247032 positive edges using 15 threads

**Comment by jlmelville** [comment]
I'm afraid I don't know the answer to that. There are no particular limits imposed by uwot on top of whatever limitations are imposed by R itself.

There are almost certainly some very poor uses of memory in the implementation of uwot, but there are also some unavoidable copies made of the data in crossing to and from the R/C++ boundary which increases the memory usage beyond what might be expected.

I would have though that running uwot with a 5M x 27 matrix is feasible in a single machine's memory, so if you are able to use a machine with more RAM then that is worth trying.
