### ISSUE TITLE
problem installing this package on my rstudio

### ISSUE THREAD

**Issue by csitaula** [jlmelville/uwot#7]
It asks for rtools whille installing and could not install.

**Comment by csitaula** [comment]
*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.4/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.4/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="uwot.dll" OBJECTS="RcppExports.o gradient.o nn_parallel.o optimize.o perplexity.o smooth_knn.o supervised.o transform.o"' had status 127
ERROR: compilation failed for package 'uwot'
* removing 'C:/Users/user/Documents/R/win-library/3.4/uwot'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by jlmelville** [comment]
Hi, have you installed Rtools? Building uwot requires compilation of C++ code, so on Windows, you need Rtools installed. You can get it from https://cran.r-project.org/bin/windows/Rtools/

**Comment by csitaula** [comment]
It let me install Rtools. But again after I installed Rtools successfully, it showed this result! Let me try once.

**Comment by jlmelville** [comment]
Great. I have updated the installation of the README.md file to make it clear Windows users need to install Rtools.
