### ISSUE TITLE
n_components: why only "can reasonably be set to any integer value in the range 2 to 100" but not 1?

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [jlmelville/uwot#74]
I was wondering why n_components should not be set to 1. Are there reasons for it not to be reasonable with n_components = 1?

**Comment by jlmelville** [comment]
I took the documentation for the parameters directly from the Python UMAP code to minimize the risk of me making an incorrect statement by paraphrasing. But in the code both the Python version and uwot allow `n_components = 1` and I know of no theoretical reason why this would be disallowed.

**Comment by PedroMilanezAlmeida** [comment]
Good to know, thank you for the quick reply!
