### ISSUE TITLE
Behavior with equidistant data

### ISSUE THREAD

**Issue by jlmelville** [jlmelville/uwot#85]
A [datascience stackexchange question](https://datascience.stackexchange.com/questions/103119/what-are-the-main-differences-between-uwot-and-umap-packages-in-r) gives an example of an odd-looking result for equidistant high-dimensional data. I should look into that.

**Comment by SamGG** [comment]
It would be easier if the OP gave the code to reproduce the graphics, especially to change the NN calculation as you suggested, which he could have tried.
Switching from Annoy to FNN and got a similar coil effect, even more pronounced.
Reordering data, does not change the result.
Adding noise leads to a figure similar to Python implementation.
```
# data generation
datum = diag(, nrow = 4001, ncol = 4000)
datum[1:9, 1:9]
datum[3991:4001, 3991:4000]
# default parameters
datum_umap = umap(datum, init = "random")
plot(datum_umap)
# alternative NN
datum_umap = umap(datum, init = "random", nn_method = "fnn")
plot(datum_umap)
# reordering data
set.seed(0)
datum = datum[sample.int(nrow(datum)),]
datum_umap = umap(datum, init = "random", nn_method = "fnn")
plot(datum_umap)
# adding some noise
datum = datum + matrix(rnorm(prod(dim(datum)), sd = 0.02), 
                       nrow = nrow(datum), ncol = ncol(datum))
datum_umap = umap(datum, init = "random", nn_method = "fnn")
plot(datum_umap)
```
![image](https://user-images.githubusercontent.com/3333348/144492150-ac23362f-179c-40b3-a6d5-6d241c009461.png)
![image](https://user-images.githubusercontent.com/3333348/144492182-e21c9674-6609-42bd-bdc7-e9ffba7db645.png)
![image](https://user-images.githubusercontent.com/3333348/144492204-7d183eec-1be1-42ce-8c16-28d3462be93d.png)
![image](https://user-images.githubusercontent.com/3333348/144492287-472bcead-41f7-4f49-80a5-201e3d7894a6.png)

**Comment by jlmelville** [comment]
Thank you for this investigation @SamGG. For your `datum` dataset, the 4001st row is genuinely the nearest neighbor of all the other points. Is there a line of code missing, where the final point in the simplex should be located along the (1, 1, 1, .... 1) direction? Not that it really matters. For the record, my `simplex` function (based on a [CS stack exchange answer](https://cs.stackexchange.com/a/69470)) looks like:

```R
simplex <- function(n) {
  X <- diag(nrow = n, ncol = n)
  rbind(X, rep((1 - sqrt(n + 1)) / n, n))
}
```

Anyway, the results are very similar. Coloring points by index shows there is obvious bias in the neighbors (this one uses FNN and initializes from PCA):

![simplex4k_fnn](https://user-images.githubusercontent.com/1936393/144560834-64767da5-c5c9-4990-baf3-8729687cf2a7.png)

I get a similar structure with Annoy. Looking at the returned nearest neighbor indices, everyone gets the same neighbors in the event of tied distances (on my machine, with Annoy you always get neighbors `1:14`, with FNN it's `3988:4001`).

With `verbose = TRUE` you will get a message about the number of smooth knn distance failures, which is usually a good diagnostic that something bad has occurred. I can't think of a good way to rescue the situation automatically though: there just aren't 15 non-degenerate neighbors to be found in this (admittedly artificial) case.

If the uniform result was from the Python version then that suggests that the failure mode of the pynndescent package results in a more random distribution of neighbors which at least doesn't fool the user into seeing some kind of spurious structure that isn't there. I suppose I should get back to finishing rnndescent.

This seems very unlikely to occur in a real dataset unless there are large numbers of duplicate rows, so I'm not *that* worried about it. Probably a bigger risk with low dimensional bit strings, though. But again, don't think there's much that can be done except be more obvious about warning about it.

**Comment by SamGG** [comment]
Thank you very much for your thorough analysis and comments.

My data generation was a quick way to get "the same 4001 equidistant points in R4000", but it was wrong for the 4001st point. I am not sure wether this last point is needed here.

Such data sets are not frequent. I have seen coil effects in parts of some rare figures where many events got the same value in many dimensions, e.g. zero in the single cell RNAseq. After studying this effect a bit, I considered that adding a bit of noise in the data should not make the real message of the data disappear. That's the reason I tried it here. If I understand your analysis correctly, we have observed what I would call a "numerical artifact".

Beyond the comparison between the implementations, I wonder what graph this dataset should have resulted in? The figure from the Python implementation (if it is the case) or from adding a little noise is fine with me. I interpret it as all points being part of a homogeneous group. I hope no one will see any bigger difference between diametrically opposed points than between the center and the periphery.

For comparison, I have done PCA approaches: SVD, irlba, SVD(data+noise). Here irlba of the initial data and SVD of the noisy data correspond to the representation I have of these points, ie a big bag of "similar" points, and I do prefer the disk of dots of UMAP.


![image](https://user-images.githubusercontent.com/3333348/144584823-c79e8844-e820-492d-acb2-b3dfd1aa2a28.png)

![image](https://user-images.githubusercontent.com/3333348/144577370-b893fe3a-e58f-41e1-b34d-96d47d311fc9.png)

![image](https://user-images.githubusercontent.com/3333348/144584945-1ed6b3e8-1e7f-44fc-92b8-4f5597b490c9.png)

```
datum = diag(1, nrow = 4001, ncol = 4000)
datum_svd = svd(datum, 2, 2)
plot(datum_svd$u, col = c(rep("black", 4000), "red"), main = "svd")
datum_irl = irlba::irlba(datum, 2, scale = FALSE, center = FALSE)
plot(datum_irl$u, col = c(rep("black", 4000), "red"), main = "irl")
datum = datum + matrix(rnorm(prod(dim(datum)), sd = 0.02), 
                       nrow = nrow(datum), ncol = ncol(datum))
datum_svd = svd(datum, 2, 2)
plot(datum_svd$u, col = c(rep("black", 4000), "red"), main = "svd")
```

**Comment by jlmelville** [comment]
Yes @SamGG the results are a numerical artifact due to the failure of the nearest neighbor search: the user asked for `n_neighbors` near neighbors, but every point has 4000 near neighbors. What should be done in this case? Randomly choosing `n_neighbors` is probably a better outcome in that case than what FNN and Annoy do, but this has broken the assumptions that UMAP (and any other graph-based dimensionality reduction method) relies on.

**Comment by jlmelville** [comment]
I used the current state of [rnndescent](https://github.com/jlmelville/rnndescent) to generate nearest neighbors via nearest neighbor descent starting from a random graph, and got a much more random selection of neighbors, which in turn led to the uniform blob UMAP result.

Wasn't really expecting anything different, but it's good to confirm it. That's one mystery cleared up. I think I will close this as there is no remedy in uwot available until I (or someone else) publishes a nearest neighbor descent package close to the performance/features of pynndescent.
