### ISSUE TITLE
check_graph in umap_transform

### ISSUE THREAD

**Issue by yuhanH** [jlmelville/uwot#86]
I notice that in the new version of uwot (0.1.11), `check_graph` is added in the `umap_transform` function. 
Because of `check_graph`, the precomputed neighbors are required to have the same number of neighbors in the reference umap. 
I am wondering why you add this checking in the `umap_transform`. It seems that when precomputed neighbors has the different number of neighbors with reference, `umap_transform` still works nicely.

**Comment by jlmelville** [comment]
I'm sorry if this change has broken your workflow. This was done to be consistent with how `umap_transform` currently works without pre-computed neighbors: it wasn't intended that this should work.

I briefly checked the Python implementation, and as far as I can tell, this isn't a feature that is supported there. Conceptually it doesn't make a lot of sense to me either: the embedded space you are adding the new points was generated from a graph with a certain value of `n_neighbors`, so you would want that to be the same for new data too.

If there is a theoretical basis to it, can you share any details of what is leading you to want a different number of neighbors between the original and the new data?

**Comment by yuhanH** [comment]
Agree.  A consistent `n_neighbors` in reference UMAP and query-ingested UMAP is more reasonable. 
Thanks.
