### ISSUE TITLE
Optimization of n_components and spread

### ISSUE THREAD

**Issue by felipe-mansoldo** [jlmelville/uwot#89]
Hello,
Congratulations on developing this great implementation.
Is there any way to optimize the parameters: n_components and spread?
Are there any metrics?
I'm using umap_transform for prediction. I thought of looping through several combinations and evaluating the prediction. But maybe there is some more optimized way.

thank you, my best

**Comment by jlmelville** [comment]
>  Is there any way to optimize the parameters: n_components and spread? Are there any metrics?

Unfortunately nothing that I am aware of. If you are looking for something like the "% of variance explained" in PCA, there isn't anything like that. Externally evaluating the results via `umap_transform` is as good a way as any. That sort of an approach is as prone to overfitting as any other parameter tuning method, but I am sure you know what you are doing there.

In terms of those specific parameters, I would be careful with how you change `spread` and make sure you have a good feel for how changes in that value affect visualizations in 2D (and ideally 3D too). I'm not sure if the safe range of values for `spread` in 2D would still be sensible when e.g. `n_components = 10`.

**Comment by felipe-mansoldo** [comment]
Hi,
Understood! Thanks for the reply.
my best
